### ISSUE TITLE
problem with visualizer

### ISSUE THREAD

**Issue by De-Novo-Research** [Steema/TeeBI#17]
When I try to use the variable visualizer in the Delphi IDE to visualize a TDataItem, I get an error message "Error: Cannot find data importer class for store: BISamples." Then it crashes the IDE. Any ideas?

**Comment by davidberneda** [comment]
This is a bug I fixed sometime ago, maybe your design-time packages are older than current sources?
Anyway, the problem probably is the TeeBIRecompile.exe did not add an entry for "BISamples" alias into the registry:

Computer\HKEY_CURRENT_USER\Software\Steema Software\TeeBI\Store

"Stores" (aliases) can be added using the TeeBI Data Manager -> Manage... top-right button, by default there might be two, "BISamples" pointing to c:\xxx\bi\sampledata folder, and "Steema" which is a web alias, pointing to host address teebi.steema.cat at port 15015.

Warning: I have pending to verify Debug Visualizers with RAD ide versions 12.3 and up, last time I got IDE crashes, something has been changed since versions 10.x and 11.x.

**Comment by De-Novo-Research** [comment]
Hi David. Wondering if you had a chance to look at this. The problem still persists in Delphi 13

**Comment by davidberneda** [comment]
I'm looking at this right now, there are new interfaces to support, I guess, looking at the source of RAD 13 TBytes debug visualizer:

C:\Program Files (x86)\Embarcadero\Studio\37.0\source\Visualizers\BytesVisualizer.pas

IOTAThreadNotifier160  is now implemented, and I'm trying to add it to our TeeBI debug visualizer:

https://github.com/Steema/TeeBI/blob/master/sources/packages/TeeBIDebugFrame.pas

but so far I get the same problem, the stuck dialog the freezes and never shows.

Almost everything works because when visualizing a TDataItem, it first gets saved to your temp folder with a random name, ie:

C:\Users\david\AppData\Local\Temp\tmp32AF.tmp

This file is just the TDataItem in binary format, that is then read with:

var Data1:= TDataItemPersistence.Load('......\tmp32AF.tmp'); // <-- load back from temp file

Then the Data1 is simply visualized with a TDataViewer dialog.

That dialog works fine at design-time inside the ide, because is the same as top menu TeeBI->Data Manager, Data, View Data...

So I'm clueless why it gets frozen. If the TBytes works fine then I'll keep following the differences with my (old 2016) visualizer code, lets see if the problem is at:

function TDataItemDebugFrame.EvaluateStringValue(const Context: TDebugContext; Expression:String):String;

because inside this there is a "repeat" loop that waits for a thread to complete, which might be the new IOTA interface 160.
